name: Deploy on main push

on:
  push:
    branches:
      - master  # Trigger only when pushing to the main branch

jobs:
  deploy:
    runs-on: [self-hosted, stage]  # Recommended: include 'self-hosted' label

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List repo files (debug)
        run: ls -al

      - name: Run deploy script
        run: ./deploy.sh
